name: timew-spirotot
summary: Timewarrior
version: 1.1.1
description: |
    Timewarrior is Free and Open Source Software that tracks time from the
    command line.

grade: stable
confinement: strict

apps:
    timew:
        command: timew
        plugs: [home]

parts:
    cmake-build:
        source: https://taskwarrior.org/download/timew-1.1.1.tar.gz
        source-checksum: sha256/1f7d9a62e55fc5a3126433654ccb1fd7d2d135f06f05697f871897c9db77ccc9
        plugin: cmake
        configflags: 
            - -DCMAKE_BUILD_TYPE=release
